CREATE TABLE t_reliable_command (
    routing_key VARCHAR(128) NOT NULL,
    namespace VARCHAR(64) NOT NULL,
    command_id VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    execution_mode VARCHAR(32) NOT NULL,
    owner_id VARCHAR(128) NOT NULL,
    request_fingerprint VARCHAR(128) NOT NULL,
    fingerprint_version VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    result_payload CLOB,
    failure_category VARCHAR(64),
    failure_message VARCHAR(512),
    business_reference VARCHAR(256),
    lease_owner VARCHAR(128),
    lease_until TIMESTAMP(3),
    fencing_token BIGINT NOT NULL DEFAULT 1,
    last_heartbeat_at TIMESTAMP(3),
    attempt_count INT NOT NULL DEFAULT 1,
    next_reconcile_at TIMESTAMP(3),
    reconcile_attempt_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (routing_key, namespace, command_id)
);

CREATE INDEX idx_reliable_command_reconcile
    ON t_reliable_command (status, next_reconcile_at);
CREATE INDEX idx_reliable_command_lease
    ON t_reliable_command (status, lease_until);

CREATE TABLE t_reliable_command_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routing_key VARCHAR(128) NOT NULL,
    namespace VARCHAR(64) NOT NULL,
    command_id VARCHAR(128) NOT NULL,
    operator_id VARCHAR(128) NOT NULL,
    old_status VARCHAR(32),
    new_status VARCHAR(32) NOT NULL,
    reason VARCHAR(128) NOT NULL,
    evidence VARCHAR(512),
    created_at TIMESTAMP(3) NOT NULL
);

CREATE INDEX idx_reliable_command_audit_key
    ON t_reliable_command_audit (routing_key, namespace, command_id, id);

CREATE TABLE t_reliable_outbox_event (
    namespace VARCHAR(64) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    deduplication_key VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(128) NOT NULL,
    payload CLOB NOT NULL,
    event_version BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    next_publish_at TIMESTAMP(3) NOT NULL,
    publish_owner VARCHAR(128),
    publish_lease_until TIMESTAMP(3),
    publish_fencing_token BIGINT NOT NULL DEFAULT 0,
    publish_attempt_count INT NOT NULL DEFAULT 0,
    broker_message_id VARCHAR(128),
    published_at TIMESTAMP(3),
    failure_category VARCHAR(64),
    failure_message VARCHAR(512),
    created_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (namespace, event_id),
    CONSTRAINT uk_reliable_outbox_dedupe UNIQUE (namespace, deduplication_key)
);

CREATE INDEX idx_reliable_outbox_publish
    ON t_reliable_outbox_event (namespace, status, next_publish_at);
CREATE INDEX idx_reliable_outbox_lease
    ON t_reliable_outbox_event (namespace, status, publish_lease_until);

CREATE TABLE t_reliable_inbox_consumption (
    namespace VARCHAR(64) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    consumer_name VARCHAR(128) NOT NULL,
    event_version BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INT NOT NULL,
    max_attempts INT NOT NULL,
    next_retry_at TIMESTAMP(3),
    lease_owner VARCHAR(128),
    lease_until TIMESTAMP(3),
    fencing_token BIGINT NOT NULL DEFAULT 0,
    failure_category VARCHAR(64),
    failure_message VARCHAR(512),
    started_at TIMESTAMP(3),
    finished_at TIMESTAMP(3),
    created_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (namespace, event_id, consumer_name)
);

CREATE INDEX idx_reliable_inbox_lease
    ON t_reliable_inbox_consumption (namespace, consumer_name, status, lease_until);
CREATE INDEX idx_reliable_inbox_retry
    ON t_reliable_inbox_consumption (namespace, consumer_name, status, next_retry_at);

CREATE TABLE t_business_effect (
    command_id VARCHAR(128) PRIMARY KEY,
    effect_value VARCHAR(128) NOT NULL
);
