-- 该表必须部署在实际业务副作用所在的服务数据库或每一个业务分片中。
-- 不要把它集中到独立远程服务，否则 LOCAL_ATOMIC 无法与业务写入共享本地事务。
CREATE TABLE IF NOT EXISTS `t_reliable_command` (
    `routing_key` VARCHAR(128) NOT NULL COMMENT '后端业务分片路由键',
    `namespace` VARCHAR(64) NOT NULL COMMENT '命令或消费者命名空间',
    `command_id` VARCHAR(128) NOT NULL COMMENT '稳定命令标识',
    `command_type` VARCHAR(64) NOT NULL COMMENT '稳定业务命令类型',
    `execution_mode` VARCHAR(32) NOT NULL COMMENT 'LOCAL_ATOMIC REMOTE_EFFECT INBOX_CONSUME',
    `owner_id` VARCHAR(128) NOT NULL COMMENT '用户租户或消费者标识',
    `request_fingerprint` VARCHAR(128) NOT NULL COMMENT '规范化请求摘要',
    `fingerprint_version` VARCHAR(32) NOT NULL COMMENT '摘要规则版本',
    `status` VARCHAR(32) NOT NULL COMMENT '可靠命令状态',
    `result_payload` TEXT NULL COMMENT '成功结果序列化文本',
    `failure_category` VARCHAR(64) NULL COMMENT '失败或未知分类',
    `failure_message` VARCHAR(512) NULL COMMENT '限长故障摘要',
    `business_reference` VARCHAR(256) NULL COMMENT '安全业务引用',
    `lease_owner` VARCHAR(128) NULL COMMENT '当前租约实例',
    `lease_until` DATETIME(3) NULL COMMENT '租约截止时间',
    `fencing_token` BIGINT NOT NULL DEFAULT 1 COMMENT '围栏令牌',
    `last_heartbeat_at` DATETIME(3) NULL COMMENT '最近心跳时间',
    `attempt_count` INT NOT NULL DEFAULT 1 COMMENT '真实执行认领次数',
    `next_reconcile_at` DATETIME(3) NULL COMMENT '下一次对账时间',
    `reconcile_attempt_count` INT NOT NULL DEFAULT 0 COMMENT '对账认领次数',
    `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
    `updated_at` DATETIME(3) NOT NULL COMMENT '修改时间',
    PRIMARY KEY (`routing_key`, `namespace`, `command_id`),
    KEY `idx_reliable_command_reconcile` (`namespace`, `status`, `next_reconcile_at`),
    KEY `idx_reliable_command_lease` (`namespace`, `status`, `lease_until`),
    KEY `idx_reliable_command_owner` (`owner_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='可靠命令执行记录';

CREATE TABLE IF NOT EXISTS `t_reliable_command_audit` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '审计流水主键',
    `routing_key` VARCHAR(128) NOT NULL COMMENT '后端业务分片路由键',
    `namespace` VARCHAR(64) NOT NULL COMMENT '命令命名空间',
    `command_id` VARCHAR(128) NOT NULL COMMENT '稳定命令标识',
    `operator_id` VARCHAR(128) NOT NULL COMMENT '执行实例或恢复器标识',
    `old_status` VARCHAR(32) NULL COMMENT '原状态',
    `new_status` VARCHAR(32) NOT NULL COMMENT '新状态',
    `reason` VARCHAR(128) NOT NULL COMMENT '状态迁移原因',
    `evidence` VARCHAR(512) NULL COMMENT '安全证据摘要',
    `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY `idx_reliable_command_audit_key` (`routing_key`, `namespace`, `command_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='可靠命令状态迁移审计';

CREATE TABLE IF NOT EXISTS `t_reliable_outbox_event` (
    `namespace` VARCHAR(64) NOT NULL COMMENT '事件业务域',
    `event_id` VARCHAR(128) NOT NULL COMMENT '服务端稳定事件标识',
    `deduplication_key` VARCHAR(128) NOT NULL COMMENT '业务去重键',
    `event_type` VARCHAR(64) NOT NULL COMMENT '稳定事件类型',
    `aggregate_id` VARCHAR(128) NOT NULL COMMENT '业务聚合标识',
    `payload` TEXT NOT NULL COMMENT '不可变安全载荷',
    `event_version` BIGINT NOT NULL COMMENT '事件协议版本',
    `status` VARCHAR(32) NOT NULL COMMENT 'PENDING PUBLISHING PUBLISHED',
    `next_publish_at` DATETIME(3) NOT NULL COMMENT '最早发布时间',
    `publish_owner` VARCHAR(128) NULL COMMENT '发布租约实例',
    `publish_lease_until` DATETIME(3) NULL COMMENT '发布租约截止时间',
    `publish_fencing_token` BIGINT NOT NULL DEFAULT 0 COMMENT '发布围栏令牌',
    `publish_attempt_count` INT NOT NULL DEFAULT 0 COMMENT '发布认领次数',
    `broker_message_id` VARCHAR(128) NULL COMMENT '消息代理标识',
    `published_at` DATETIME(3) NULL COMMENT '消息代理确认时间',
    `failure_category` VARCHAR(64) NULL COMMENT '最近发布失败分类',
    `failure_message` VARCHAR(512) NULL COMMENT '最近发布失败摘要',
    `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
    `updated_at` DATETIME(3) NOT NULL COMMENT '修改时间',
    PRIMARY KEY (`namespace`, `event_id`),
    UNIQUE KEY `uk_reliable_outbox_dedupe` (`namespace`, `deduplication_key`),
    KEY `idx_reliable_outbox_publish` (`namespace`, `status`, `next_publish_at`),
    KEY `idx_reliable_outbox_lease` (`namespace`, `status`, `publish_lease_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='可靠事务 Outbox';

CREATE TABLE IF NOT EXISTS `t_reliable_inbox_consumption` (
    `namespace` VARCHAR(64) NOT NULL COMMENT '事件业务域',
    `event_id` VARCHAR(128) NOT NULL COMMENT '事件标识',
    `consumer_name` VARCHAR(128) NOT NULL COMMENT '稳定消费者名称',
    `event_version` BIGINT NOT NULL COMMENT '已领取事件版本',
    `status` VARCHAR(32) NOT NULL COMMENT 'PROCESSING RETRY_WAIT SUCCEEDED FAILED',
    `attempt_count` INT NOT NULL COMMENT '消费领取次数',
    `max_attempts` INT NOT NULL COMMENT '最大消费次数',
    `next_retry_at` DATETIME(3) NULL COMMENT '下一次处理时间',
    `lease_owner` VARCHAR(128) NULL COMMENT '消费租约实例',
    `lease_until` DATETIME(3) NULL COMMENT '消费租约截止时间',
    `fencing_token` BIGINT NOT NULL DEFAULT 0 COMMENT '消费围栏令牌',
    `failure_category` VARCHAR(64) NULL COMMENT '最近失败分类',
    `failure_message` VARCHAR(512) NULL COMMENT '最近失败摘要',
    `started_at` DATETIME(3) NULL COMMENT '最近开始时间',
    `finished_at` DATETIME(3) NULL COMMENT '终态时间',
    `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
    `updated_at` DATETIME(3) NOT NULL COMMENT '修改时间',
    PRIMARY KEY (`namespace`, `event_id`, `consumer_name`),
    KEY `idx_reliable_inbox_lease` (`namespace`, `consumer_name`, `status`, `lease_until`),
    KEY `idx_reliable_inbox_retry` (`namespace`, `consumer_name`, `status`, `next_retry_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='可靠消费 Inbox';
